### ISSUE TITLE
Square brackets not supported in alias operations

### ISSUE THREAD

**Issue by Vincenzo-Petrolo** [LucasKl/riscv-function-profiling#1]
Hi,

I am facing issues when I have this alias instruction in `config.wal`
```
(alias clk TOP.u_xxx_top.u_xxx_peripherals.gen_fff_system[0].u_fff_wrapper.u_fff_top.u_fff_ctl.clk)
```
When I invoke the `profile.py`:
```sh
python3 ../vendor/riscv-function-profiling/profile.py ../../build/sw/fff/runtime.elf ../../build/sim-common/waves.fst
```
I get this error:
```
>>>>> WAL Runtime error! <<<<<
 1: ...
 2: (alias clk TOP.u_xxx_top.u_xxx_peripherals.gen_fff_system[0].u_fff_wrapper.u_fff_top.u_fff_ctl.clk)
    ^
    Error at ./config.wal:2
alias: expects an even number of arguments
```

I tried to figure it out on my own but I couldn't get the issue sorted out, can you shed some light on how can I handle such a scenario where I have a for/generate in my .fst/.vcd? Is there any special escape sequence I could use or is it just a missing feature?

**Comment by LucasKl** [comment]
Square brackets should be changed by WAL to <> since they are a language feature to access slices.
Can you try changing your signal to ` TOP.u_xxx_top.u_xxx_peripherals.gen_fff_system<0>.u_fff_wrapper.u_fff_top.u_fff_ctl.clk`?

**Comment by Vincenzo-Petrolo** [comment]
Hi thanks for reaching back!
I can confirm that works, thank you!
